--- # This is condition playbook
- hosts: devlopment[0]
  user: ansible
  become: yes
  connection: ssh
  tasks:
    - name: install apache on debian
      command: apt-get install apache2
      when: ansible_os_family == "Debian"
    - name: install httpd on amazon linux machine
      command: yum install httpd -y
      when: ansible_os_family == "RedHat"
