--- # This handler playbook
- hosts: all
  user: ansible
  become: yes
  connection: ssh
  tasks:
    - name: Install httpd on all nodes
      action: yum name=httpd state=present
      notify: restart httpd
  handlers:
    - name: restart httpd
      action: service name=httpd state=restarted

